name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: macOS-latest, shell: bash }
          - { os: ubuntu-latest, shell: bash }
          - { os: windows-latest, shell: cmd }

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.0"

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .
